version: '3'

services:
  app:
    build:
      args:
       user: ubuntu
       uid: 1000
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app

  nginx:
      image: nginx:alpine
      container_name: nginx
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./:/var/www/
        - ./docker/conf.d/:/etc/nginx/conf.d/
        - ./docker/certbot/www:/var/www/certbot
        - ./docker/certbot/conf:/etc/letsencrypt
      networks:
        - app
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
      image: certbot/certbot
      volumes:
        - ./docker/certbot/conf:/etc/letsencrypt
        - ./docker/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  app:
    driver: bridge



